language: csharp
solution: IsochronDrafter.sln
sudo: false

install:
  - pip install --user python-coveralls pytest pytest-cov pyopenssl ndg-httpsclient pyasn1

script:
  - py.test test_me.py --doctest-modules -v --cov coveralls --cov-report term-missing

after_script:
  - coveralls

