language: csharp
solution: IsochronDrafter.sln
sudo: false

install:
  - pip install --user python-coveralls pytest pytest-cov pyopenssl ndg-httpsclient pyasn1

script:
  - py.test --cov=test_me.py --cov-report term-missing

after_script:
  - coveralls

