language: csharp
solution: IsochronDrafter.sln
sudo: false

install:
  - pip install --user python-coveralls pytest pyopenssl ndg-httpsclient pyasn1

script:
  - py.test --tb=short test_me.py

after_script:
  - coveralls

