language: csharp
solution: IsochronDrafter.sln
sudo: false

install:
  - pip install --user python-coveralls pytest pyopenssl ndg-httpsclient pyasn1

script:
  - py.test --tb=short test_me.py --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing

after_script:
  - coveralls

