language: csharp
solution: IsochronDrafter.sln
sudo: false

install:
  - pip install --user coveralls
  - nuget restore IsochronDrafter.sln
  - nuget install NUnit.Runners -Version 3.6.1 -OutputDirectory testrunner

script:
  - xbuild /p:Configuration=Release IsochronDrafter.sln
  - mono .\packages\NUnit.ConsoleRunner.3.6.1\toolsnunit3-console.exe .\IsochronDrafterTests2\bin\Release\IsochronDrafterTests2.dll
  
after_script:
  - coveralls

