language: csharp
solution: IsochronDrafter.sln
sudo: false
notifications:
    slack: dblockhq:qSfn6zRrJcTv2OOMV5LjKean
addons:
    srcclr: true
    
install:
  - pip install --user coveralls pyopenssl ndg-httpsclient pyasn1
  - nuget restore IsochronDrafter.sln
  - nuget install NUnit.Runners -Version 3.6.1 -OutputDirectory testrunner

script:
  - xbuild /p:Configuration=Release IsochronDrafter.sln
  - mono .\\packages\\NUnit.ConsoleRunner.3.6.1\\tools\\nunit3-console.exe .\\IsochronDrafterTests2\\bin\\Release\\IsochronDrafterTests2.dll
  
after_script:
  - coveralls

